---
# Debian specific tasks

- name: Install required debian packages
  apt: name={{ item }} state=present update_cache=yes force=yes
  with_items:
      - postgresql
      - postgresql-contrib
      - postgresql-{{ postgresql_version }}-postgis-scripts=2.3*
      - postgresql-server-dev-all
      - postgresql-{{ postgresql_version }}-postgis-2.3
      - postgis=2.3*
      - python3-pip
      - python-pip
      - python3-dev
      - python-dev
      - postgresql-server-dev-{{ postgresql_version }}
      - libpq-dev
      - libpq5={{ postgresql_version }}*

