---

- name: Show groups for this host
  debug: var=group_names
  notify: include OS-specific handlers

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: ssh disable password auth
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
