---
# Tasks to install postgresql
#
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: Generate taiga secret key
  shell: "pwgen -s -n 40 1"
  register: taiga_secret_key

- name: Taiga secret key
  debug: var=taiga_secret_key

- name: Create postgresql user
  become_user: postgres 
  postgresql_user: name=taiga

- name: Create postgresql taiga database
  become_user: postgres 
  postgresql_db:
      name: taiga
      owner: taiga
      encoding: UTF-8
      template: template0

- name: setup fs
  file: path={{ item.path }} owner='root' group='root' mode=755 state=directory
  with_items:
      - path: /srv

- name: Create taiga user
  user:
      name: taiga
      home: /srv/taiga

- name: setup fs
  file: path={{ item.path }} owner='taiga' group='taiga' mode=755 state=directory
  with_items:
      - path: /srv/taiga/logs

- name: get taiga-back
  become_user: taiga
  git:
      repo: https://github.com/taigaio/taiga-back.git
      dest: /srv/taiga/taiga-back
      version: stable

- name: get taiga-front
  become_user: taiga
  git:
      repo: https://github.com/taigaio/taiga-front-dist.git
      dest: /srv/taiga/taiga-front-dist
      version: stable

- name: get taiga-events
  become_user: taiga
  git:
      repo: https://github.com/taigaio/taiga-events.git
      dest: /srv/taiga/taiga-events

- name: virtualenv and requirements
- pip:
    virtualenv_python: python3
    requirements: /srv/taiga/taiga-back/requirements.txt
    virtualenv: /srv/taiga/venv

- name: populating db with initial basic data
- django_manage:
    command: migrate
    virtualenv: /srv/taiga/venv
    app_path: /srv/taiga/taiga-back

- name: populating db with initial user
- django_manage:
    command: loaddata
    virtualenv: /srv/taiga/venv
    app_path: /srv/taiga/taiga-back
    fixtures: initial_user initial_project_templates

- name: compile messages
- django_manage:
    command: "{{ item }}"
    virtualenv: /srv/taiga/venv
    app_path: /srv/taiga/taiga-back
  with_items:
    - collectstatic
    - compilemessages

- name: collect static
- django_manage:
    command: collectstatic
    virtualenv: /srv/taiga/venv
    app_path: /srv/taiga/taiga-back

- name: Install npm packages
  npm: name="{{ item }}" global=yes
  with_items:
      - coffee-script
