---
# Debian specific tasks

- name: Install nginx and php
  yum: name={{ item }} state=present
  with_items:
      - nginx-full
      - php5-fpm
      - php5-gd
      - php5-mysql
      - php5-pgsql
      - php5-mcrypt
      - certbot
      - postfix
