---
# Debian specific tasks

- name: Install nginx and php
  apt: name={{ item }} state=latest default_release=jessie-backports force=yes
  with_items:
      - nginx-full
      - php5-fpm
      - php5-gd
      - php5-mysql
      - php5-pgsql
      - php5-mcrypt
      - python-pkg-resources
      - python-setuptools
      - python-cryptography
      - python-psutil
      - python-openssl
      - python-acme
      - python-certbot
      - python-certbot-nginx
      - certbot
  when: ansible_distribution_release == "jessie"

- name: Install nginx and php
  apt: name={{ item }} state=latest
  with_items:
      - nginx-full
      - php5-fpm
      - php5-gd
      - php5-mysql
      - php5-pgsql
      - php5-mcrypt
      - python-pkg-resources
      - python-setuptools
      - python-cryptography
      - python-psutil
      - python-openssl
      - python-acme
      - python-certbot
      - python-certbot-nginx
      - certbot
      - postfix
  when: ansible_distribution_release != "jessie"
