---

- name: postfix service state
  service: name=postfix state=started enabled=yes

- name: set postfix main.cf options
  lineinfile: dest="{{ postfix_conf_dir }}/main.cf" regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
  with_items:
      - regexp: "^#?relayhost" 
        line: "relayhost = {{ postfix_relay_host }}"
  notify: restart postfix
