---
# RedHat/CentOS specific tasks

- name: Install nginx and php
  yum: name={{ item }} state=present
  with_items:
      - nginx
      - php
      - php-fpm
      - php-gd
      - php-pgsql
      - php-mysql
      - epel-release
      - certbot

