---

- name: Include generic variables
  include_vars: "defaults.yml"

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Remove existing ODK Aggregate
  file: path="{{ tomcat_webapp_dir }}/ODKAggregate/" state=absent 

- name: Remove existing ODK Aggregate war
  file: path="{{ tomcat_webapp_dir }}/ODKAggregate.war" state=absent 

- name: copy ODK-aggregate war
  copy: src=ODKAggregate.war dest="{{ tomcat_webapp_dir }}"
  notify: restart tomcat

- name: copy sql file
  copy: src=create_db_and_user.sql dest="/tmp/"

- name: import postgresql database
  shell: psql -f /tmp/create_db_and_user.sql
  become: true
  become_user: postgres
