---
# Debian/Ubuntu specific tasks

- name: Install required debian packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - postgresql
      - postgresql-{{postgresql_version}}-plv8
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
