---
- name: restart postgresql
  service:
      name: postgresql
      state: restarted

- name: reload circus
  shell: circusctl {{ item }}
  with_items:
    - reloadconfig
    - start taiga 
    - start taiga-celery
    - start taiga-events