---
# Debian specific tasks

- name: Install required debian packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - python3
      - python3-pip
      - python3-dev
      - postgresql-dev
